name: locapo
description: "Modern İşletme Yönetim Sistemi - Locapo ile işinizi büyütün"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase (sadece web ve mobil)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0

  # Local Storage (desktop için)
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  path: ^1.8.3

  # State Management & UI
  provider: ^6.1.1
  google_sign_in: ^7.1.1
  rxdart: ^0.28.0

  # Notifications
  flutter_local_notifications: ^17.0.0
  firebase_messaging_web: ^4.0.0
  timezone: 0.9.4
  permission_handler: ^12.0.1

  # Charts & Calendar
  fl_chart: ^1.0.0
  table_calendar: ^3.0.9

  # Utilities
  intl: ^0.20.2
  html: ^0.15.4
  url_launcher: ^6.2.5
  geolocator: ^14.0.2

  # Advanced Document Management
  flutter_image_compress: ^2.1.0
  google_ml_kit: ^0.20.0
  camera: ^0.11.2
  image: ^4.1.7
  http: ^1.1.2
  # pdf_render: ^1.4.12  # Geçici olarak devre dışı - Registrar API uyumsuzluğu
  
  # Icons
  cupertino_icons: ^1.0.6

  # New dependencies
  uuid: ^4.3.1
  lottie: ^3.3.0
  encrypt: ^5.0.1
  file_picker: ^6.2.1
  # printing: ^5.12.0  # Geçici olarak devre dışı - pdf_render bağımlılığı
  csv: ^6.0.0
  pdf: ^3.10.8
  path_provider: ^2.1.2
  excel: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
  mockito: ^5.4.4
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/google_logo.png
    - assets/images/placeholder.png
  generate: true
  
  # Plugin platform configuration temporarily disabled
  # plugin:
  #   platforms:
  #     linux:
  #       default_package: null
  #     macos:
  #       default_package: null
  #     windows:
  #       default_package: null
# Auto-cleaned and rebuilt by Cursor
# Assets updated by Cursor
# Cleaned for Web Build by Cursor

dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master