// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBneG6gidkxHa4rdLW5P0QzKSprSn1lj0o',
    appId: '1:308323114774:web:cb0d152574c2952dcbba37',
    messagingSenderId: '308323114774',
    projectId: 'randevu-takip-app',
    authDomain: 'randevu-takip-app.firebaseapp.com',
    storageBucket: 'randevu-takip-app.firebasestorage.app',
    measurementId: 'G-P4HEJJ2Z1P',
  );
  
  // FCM Web Push için VAPID Key - Ayrı constanta tanımlandı
  // Firebase Console > Project Settings > Cloud Messaging > Web Push certificates'dan alınacak
  static const String vapidKey = 'BJ7LMlB1LNtAVtiqk5C_nvzANRpKoLgncFChYu36X3NeClE0H-EcINhS9MFTCSuNanHkitPwdMUI7uX_cEk4Xno';

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8LKl-amplgqdlh6JKVT87wSSlQcAGCIg',
    appId: '1:308323114774:android:42013039b587f7d8cbba37',
    messagingSenderId: '308323114774',
    projectId: 'randevu-takip-app',
    storageBucket: 'randevu-takip-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ6XWZFP0Vw1ZEaLc0DBFMqhyzFHnnT7M',
    appId: '1:308323114774:ios:31565af9e265f749cbba37',
    messagingSenderId: '308323114774',
    projectId: 'randevu-takip-app',
    storageBucket: 'randevu-takip-app.firebasestorage.app',
    iosBundleId: 'com.example.randevuErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ6XWZFP0Vw1ZEaLc0DBFMqhyzFHnnT7M',
    appId: '1:308323114774:ios:31565af9e265f749cbba37',
    messagingSenderId: '308323114774',
    projectId: 'randevu-takip-app',
    storageBucket: 'randevu-takip-app.firebasestorage.app',
    iosBundleId: 'com.example.randevuErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBneG6gidkxHa4rdLW5P0QzKSprSn1lj0o',
    appId: '1:308323114774:web:0834679bf5c9764ccbba37',
    messagingSenderId: '308323114774',
    projectId: 'randevu-takip-app',
    authDomain: 'randevu-takip-app.firebaseapp.com',
    storageBucket: 'randevu-takip-app.firebasestorage.app',
    measurementId: 'G-QE4HJSELJY',
  );

}