// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqpBvGPlKNxEF8cjfFLzqp5cjBGg7qvUk',
    appId: '1:308323114774:web:cb0d152574c2952dcbba37',
    messagingSenderId: '308323114774',
    projectId: 'randevu-takip-app',
    authDomain: 'randevu-takip-app.firebaseapp.com',
    storageBucket: 'randevu-takip-app.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqpBvGPlKNxEF8cjfFLzqp5cjBGg7qvUk',
    appId: '1:308323114774:android:42013039b587f7d8cbba37',
    messagingSenderId: '308323114774',
    projectId: 'randevu-takip-app',
    storageBucket: 'randevu-takip-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqpBvGPlKNxEF8cjfFLzqp5cjBGg7qvUk',
    appId: '1:308323114774:ios:31565af9e265f749cbba37',
    messagingSenderId: '308323114774',
    projectId: 'randevu-takip-app',
    storageBucket: 'randevu-takip-app.appspot.com',
    iosBundleId: 'com.randevuerp.business',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqpBvGPlKNxEF8cjfFLzqp5cjBGg7qvUk',
    appId: '1:308323114774:ios:31565af9e265f749cbba37',
    messagingSenderId: '308323114774',
    projectId: 'randevu-takip-app',
    storageBucket: 'randevu-takip-app.appspot.com',
    iosBundleId: 'com.randevuerp.business',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqpBvGPlKNxEF8cjfFLzqp5cjBGg7qvUk',
    appId: '1:308323114774:web:0834679bf5c9764ccbba37',
    messagingSenderId: '308323114774',
    projectId: 'randevu-takip-app',
    authDomain: 'randevu-takip-app.firebaseapp.com',
    storageBucket: 'randevu-takip-app.appspot.com',
  );
}