name: Flutter Build & Analyze

on:
  pull_request:
    branches:
      - main

jobs:
  flutter_analyze:
    name: Analyze & Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test 